kind: Template
apiVersion: v1
metadata:
    name: af-connect
    annotations:
        openshift.io/display-name: 'AF-Connect'
        description: "An Node.js application for handling consent."
        tags: 'nodejs,consent'
        iconClass: icon-nodejs
        openshift.io/documentation-url: '${SOURCE_REPOSITORY_URL}'
labels:
    template: '${APPLICATION_NAME}'
    app: '${APPLICATION_NAME}'
objects:
    -
        kind: Service
        apiVersion: v1
        metadata:
            name: '${APPLICATION_NAME}'
            annotations:
                description: 'Exposes and load balances the application pods'
        spec:
            ports:
                - 
                    name: "3000-tcp"
                    port: 3000
                    protocol: TCP
                    targetPort: 3000
                -
                    name: "4443-tcp" 
                    port: 4443
                    protocol: TCP
                    targetPort: 4443
                -
                    name: "8080-tcp" 
                    port: 8080
                    protocol: TCP
                    targetPort: 8080
            selector:
                deploymentconfig: '${APPLICATION_NAME}'
    -
        kind: DeploymentConfig
        apiVersion: v1
        metadata:
            name: '${APPLICATION_NAME}'
            annotations:
                description: 'Defines how to deploy the application server'
                template.alpha.openshift.io/wait-for-ready: 'true'
        spec:
            strategy:
                type: Rolling
            triggers:
                -
                    type: ImageChange
                    imageChangeParams:
                        automatic: true
                        containerNames: 
                            - '${APPLICATION_NAME}'
                        from:
                            kind: ImageStreamTag
                            namespace: '${NAMESPACE}'
                            name: '${APPLICATION_NAME}:latest'
                -
                    type: ConfigChange
            replicas: 1
            selector:
                name: '${APPLICATION_NAME}'
            template:
                metadata:
                    name: '${APPLICATION_NAME}'
                    labels:
                        name: '${APPLICATION_NAME}'
                spec:
                    containers: 
                        -
                            name: '${APPLICATION_NAME}'
                            image: >-
                                image-registry.openshift-image-registry.svc:5000/'${NAMESPACE}'/'${APPLICATION_NAME}'
                            ports:
                                - 
                                    containerPort: 3000
                                    protocol: TCP
                                - 
                                    containerPort: 4443
                                    protocol: TCP
                                - 
                                    containerPort: 8080
                                    protocol: TCP
                            env: 
                                - name: USE_SSL
                                  value: '${USE_SSL}'
                                - name: HOST
                                  value: '${HOST}'
                                - name: PORTABILITY_URL
                                  value: '${PORTABILITY_URL}'
                                - name: AF_JWT_URL
                                  value: '${AF_JWT_URL}' 
                                - name: AF_LOGIN_URL
                                  value: '${AF_LOGIN_URL}' 
                    restartPolicy: Always
                    terminationGracePeriodSeconds: 30
                    dnsPolicy: ClusterFirst
                    securityContext: {}
                    schedulerName: default-scheduler
                    
parameters:
    -
        name: APPLICATION_NAME
        displayName: Name
        description: 'The name assigned to all of the frontend objects defined in this template.'
        required: true
        value: af-connect
    -
        name: NAMESPACE
        displayName: Namespace
        description: 'The OpenShift Namespace where the ImageStream resides.'
        required: true
        value: af-connect-cicd
    -
        name: SOURCE_REPOSITORY_URL
        displayName: 'Git Repository URL'
        description: 'The URL of the repository with your application source code.'
        required: true
        value: 'https://github.com/MagnumOpuses/af-connect-outbox.git'
    -
        name: SOURCE_REPOSITORY_REF
        displayName: 'Git Reference'
        description: 'Set this to a branch name, tag or other ref of your repository if you are not using the default branch.'
        required: true
        value: stage
    -
        name: APPLICATION_DOMAIN
        displayName: 'Application Hostname'
        description: 'The exposed hostname that will route to the Node.js service, if left blank a value will be defaulted.'
        value: ""
    -
        name: GITHUB_WEBHOOK_SECRET
        displayName: 'GitHub Webhook Secret'
        description: 'Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.'
        generate: expression
        from: '[a-zA-Z0-9]{40}'
    -
        name: GENERIC_WEBHOOK_SECRET
        displayName: 'Generic Webhook Secret'
        description: 'A secret string used to configure the Generic webhook.'
        generate: expression
        from: '[a-zA-Z0-9]{40}'
    -
        name: USE_SSL
        value: ''
    -
        name: HOST
        value: localhost
    -
        name: PORTABILITY_URL
        value: 'http://af-portability:8080'
    -
        name: AF_JWT_URL
        value: 'http://af-connect-mock:9998/jwt/rest/idp/v0/klientID'
    -
        name: AF_LOGIN_URL
        value: 'https://af-connect-mock.test.services.jtech.se/AuthenticationDispatcher/Dispatch?CT_ORIG_URL=https://af-connect.test.services.jtech.se'

